title: Hello, My Name is Efilda
description: > # this means to ignore newlines until "baseurl:"
  Hello, My Name is Efilda
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/efilda/efilda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: EFILDA # add your name
author-img: efilda.jpg # add your photo
about-author: Hello, My Name is Efilda. i am a student at UIN SUSKA RIAU. Well this is my blog for a college assignment. # add description
social-twitter: efilda# add your Twitter handle
social-facebook: efilda# add your Facebook handle
social-github: efilda # add your Github handle
social-linkedin: efilda # add your Linkedin handle
social-email: efilda22@gamail.com# add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
